apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: examen-devops
type: Opaque
stringData:
  DB_PASSWORD: "secret"
  AWS_ACCESS_KEY_ID: "PLACEHOLDER"
  AWS_SECRET_ACCESS_KEY: "PLACEHOLDER"
  AWS_DEFAULT_REGION: "us-east-1"
